<?php

namespace LabelBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getLabels($order = 'lablel.id')
    {

        $qb = $this->createQueryBuilder('label')
            ->select(
                  'label.name, '
                . 'label.description '
                )
            ->where('label.deleted = false')
            ->orderBy($order);
        
        $labels = $qb->getQuery()->getScalarResult();
        
        return $labels;
    }
}
