<?php

namespace LabelBundle\Repository;

/**
 * LabelRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRelationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getEntitylabels($id, $name)
    {
        $qb = $this->createQueryBuilder('el')
            ->select('el')
            ->where('el.deleted = false AND el.entityId = :id AND el.entityName = :name')
            ->setParameter('id', $id)
            ->setParameter('name', $name);
            
        return $qb->getQuery()->getResult();
    }
}
