<?php

namespace LabelBundle\Repository;

/**
 * LabelRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
