
product_bundle:
    resource: "@ProductBundle/Resources/config/routes.yml"    
    prefix: /

page_bundle:
    resource: "@PageBundle/Resources/config/routes.yml"    
    prefix: /
    
theme_bundle:
    resource: "@ThemeBundle/Resources/config/routes.yml"    
    prefix: /
    
label_bundle:
    resource: "@LabelBundle/Resources/config/routes.yml"    
    prefix: / 
    
shop_bundle:
    resource: "@ShopBundle/Resources/config/routes.yml"    
    prefix: / 
        
user_bundle:
    resource: "@UserBundle/Resources/config/routes.yml"    
    prefix: / 
        
app_bundle:
    resource: "@AppBundle/Controller/"
    type:     annotation


admin_login:
    path:     /login/{isFront}
    defaults: { _controller: AppBundle:Security:login, isFront: false }
    
api_login_check:
    path: /api/login_check
    
admin_logout:
    path: /admin/logout    