
product_bundle:
    resource: "@ProductBundle/Resources/config/routes.yml"    
    prefix: /

page_bundle:
    resource: "@PageBundle/Resources/config/routes.yml"    
    prefix: /
    
theme_bundle:
    resource: "@ThemeBundle/Resources/config/routes.yml"    
    prefix: /
    
label_bundle:
    resource: "@LabelBundle/Resources/config/routes.yml"    
    prefix: / 
    
customer_bundle:
    resource: "@CustomerBundle/Resources/config/routes.yml"    
    prefix: / 
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_login_check:
    path: /api/login_check