product:
    resource: ProductBundle\Controller\ProductController
    type:     rest
    prefix:   /api/admin/product
    
category:
    resource: ProductBundle\Controller\CategoryController
    type:     rest
    prefix:   /api/admin/category
    
brand:
    resource: ProductBundle\Controller\BrandController
    type:     rest
    prefix:   /api/admin/brand   
    
customer:
    resource: ProductBundle\Controller\CustomerController
    type:     rest
    prefix:   /api/customer/product    