# Admin part
product_admin:
    resource: ProductBundle\Controller\ProductAdminController
    type:     rest
    prefix:   /api/admin/product
    
category_admin:
    resource: ProductBundle\Controller\CategoryAdminController
    type:     rest
    prefix:   /api/admin/category
    
brand_admin:
    resource: ProductBundle\Controller\BrandAdminController
    type:     rest
    prefix:   /api/admin/brand
    
# Shop part    
product:
    resource: ProductBundle\Controller\ProductController
    type:     rest
    prefix:   /api/shop/product    