product:
    resource: ProductBundle\Controller\ProductController
    type:     rest
    prefix:   /api/admin/product
    
category:
    resource: ProductBundle\Controller\CategoryController
    type:     rest
    prefix:   /api/admin/category