product:
    resource: ProductBundle\Controller\ProductController
    type:     rest
    prefix:   /
    
category:
    resource: ProductBundle\Controller\CategoryController
    type:     rest
    prefix:   /