# Admin part
user_admin:
    resource: UserBundle\Controller\UserAdminController
    type:     rest
    prefix:   /api/admin/user
    
# Shop part    
user:
    resource: UserBundle\Controller\UserController
    type:     rest
    prefix:   /api/shop/user
    