services:
    user.service:
        class: UserBundle\Service\UserService
        arguments: 
            - "@translator.default"
            - "@doctrine.orm.default_entity_manager"
            
    address.service:
        class: UserBundle\Service\AddressService
        arguments: 
            - "@translator.default"
            - "@doctrine.orm.default_entity_manager"            