services:    
    app.service:
        class: AppBundle\Service\AppService
        arguments: 
            - "@translator.default"
            - "@doctrine.orm.default_entity_manager"
            
    app.md5encoder:
        class: AppBundle\Service\Md5Encoder
        arguments: 
            - "%app_saltmain%"            