# Admin part
customer:
    resource: CustomerBundle\Controller\CustomerController
    type:     rest
    prefix:   /api/admin/customer
    
order:
    resource: CustomerBundle\Controller\OrderController
    type:     rest
    prefix:   /api/admin/order
    
    
# Customer access part    
basket:
    resource: CustomerBundle\Controller\BasketController
    type:     rest
    prefix:   /api/customer/basket

    