customer:
    resource: CustomerBundle\Controller\CustomerController
    type:     rest
    prefix:   /api/admin/customer
    
order:
    resource: CustomerBundle\Controller\OrderController
    type:     rest
    prefix:   /api/admin/order