services:    
    customer.service:
        class: CustomerBundle\Service\CustomerService
        arguments: 
            - "@translator.default"
            - "@doctrine.orm.default_entity_manager"
            
    address.service:
        class: CustomerBundle\Service\AddressService
        arguments: 
            - "@translator.default"
            - "@doctrine.orm.default_entity_manager"            