<?php

namespace ThemeBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getThemes($criteria = null, $order = 't.id')
    {
        $qb = $this->createQueryBuilder('t')
            ->select(
                  't.id, '
                . 't.name, '
                . 't.content '
                )
            ->where('t.deleted = false')
            ->orderBy($order);
        
        // Search by name if searchText is provided
        if (null !== $criteria) {
            if (isset($criteria['searchText']) && $criteria['searchText'] !== '') {
                $qb->andWhere('t.name LIKE :searchText')
                    ->setParameter('searchText', '%'. $criteria['searchText'] .'%');
            }                
        }
        
        return $qb->getQuery()->getScalarResult();
    }
    
    /**
     * 
     * @return type
     */
    public function getTheme($id)
    {
        $qb = $this->createQueryBuilder('t')
            ->select(
                  't.id, '
                . 't.name, '
                . 't.content '
                )
            ->where('t.id = :id')
            ->setParameter('id', $id);
        
        return $qb->getQuery()->getSingleResult();
    }    
    
}
