<?php

namespace CustomerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getOrders($order = 'ord.id')
    {
        $qb = $this->createQueryBuilder('ord')
            ->select(
                  'ord.id'
                )
            ->where('ord.deleted = false')
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }
    
    
}
