<?php

namespace CustomerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getOrders($order = 'ord.id')
    {
        $qb = $this->createQueryBuilder('ord')
            ->select(
                  'ord.id'
                )
            ->where('ord.deleted = false')
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }
    

    /**
     * 
     * @return type
     */
    public function getOrderDetails($id)
    {
        $qb = $this->createQueryBuilder('ord')
            ->select(
                  'od.id, '
                . 'od.quantity, '
                . 'od.comment, '
                . 'od.status, '
                . 'p.name as product'
                )
            ->join('ord.orderDetails', 'od')
            ->join('od.product', 'p')
            ->where('ord.deleted = false AND od.deleted = false AND ord.id = :id')
            ->setParameter('id', $id);
        
        return $qb->getQuery()->getScalarResult();

    }    
}
