<?php

namespace CustomerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailRepository extends \Doctrine\ORM\EntityRepository
{
        /**
     * 
     * @return type
     */
    public function getOrderDetails($id)
    {
        $qb = $this->createQueryBuilder('o')
            ->select(
                  'o.id, '
                . 'o.orderDate, '
                . 'od.quantity, '
                . 'od.comment, '
                . 'od.status '
                )
            ->join('o.orderDetails', 'od')
            ->where('o.deleted = false AND o.id = :id')
            ->setParameters('id', $id);
        
        $orderDetails = $qb->getQuery()->getScalarResult();

}
