<?php

namespace CustomerBundle\Repository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param type $customer
     * @return type
     */
    public function getWishlistItems($customer) 
    {
        $qb = $this->createQueryBuilder('wishlist')
            ->select(
                'wishlist.id,'
               .'p.name'
                )
            ->join('wishlist.product', 'p')
            ->where('wishlist.deleted = false AND wishlist.customer = :customer')
            ->setParameter('customer', $customer);

        return $qb->getQuery()->getScalarResult();
    }    
}
