<?php

namespace CustomerBundle\Repository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @param type $customer
     * @return type
     */
    public function getWishlistItem($customer, $product) 
    {
        $qb = $this->createQueryBuilder('wishlist')
            ->select(
                'wishlist.id,'
               .'p.id,'
               .'c.id'
                )
            ->join('wishlist.product', 'p')
            ->join('wishlist.customer', 'c')
            ->where('wishlist.deleted = false AND wishlist.customer = :customer AND wishlist.product = :product')
            ->setParameter('customer', $customer)
            ->setParameter('product', $product);

        return $qb->getQuery()->getOneOrNullResult();
    }    
}
