<?php

namespace ProductBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getBrands($order = 'brand.id')
    {
        $qb = $this->createQueryBuilder('brand')
            ->select(
                  'brand.id, '
                . 'brand.name'
                )
            ->where('brand.deleted = false')
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }
    
}
