<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getBrands($order = 'brand.id')
    {
        $qb = $this->createQueryBuilder('brand')
            ->select(
                  'brand.id, '
                . 'brand.name'
                )
            ->where('brand.deleted = false')
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }
    
    /**
     * 
     * @return type
     */
    public function getBrand($id)
    {
        $qb = $this->createQueryBuilder('b')
            ->select(
                  'b.id, '
                . 'b.name, '
                . 'b.description'
                )
            ->where('b.id = :id')
            ->setParameter('id', $id);
        
        $brand = $qb->getQuery()->getSingleResult();
        
        return $brand;
    }    
}