<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStockRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getProducts($id = null, $order = 'p.id')
    {
        $qb = $this->createQueryBuilder('ps')
            ->select(
                  'p.id, '
                . 'p.name, '
                . 'p.description,'
                . 'p.price'
                )
            ->join('ps.product', 'p')
            ->where('p.deleted = false')
            ->groupBy('p')    
            ->orderBy($order);
        
        if (null !== $id) {
            $qb->andWhere('ps.productCategory = :id')
                ->setParameter('id', $id);
        }
        
        return $qb->getQuery()->getScalarResult();
    }
}
