<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStockRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getProducts($id, $order = 'p.id')
    {
        $qb = $this->createQueryBuilder('ps')
            ->select(
                  'p.id, '
                . 'p.name, '
                . 'p.description,'
                . 'p.price'
                )
            ->join('ps.product', 'p')
            ->where('ps.productCategory = :id')
            ->setParameter('id', $id)
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }    
}
