<?php

namespace ProductBundle\Repository;

/**
 * ProductStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStockRepository extends \Doctrine\ORM\EntityRepository
{
}
