<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getCategories($order = 'category.id')
    {
        $qb = $this->createQueryBuilder('category')
            ->select(
                  'category.id, '
                . 'category.name'
                )
            ->where('category.deleted = false')
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }
    
    public function getCategory($id)
    {
        $qb = $this->createQueryBuilder('category')
            ->select(
                  'category.id, '
                . 'category.name '
                )
            ->where('category.id = :id')
            ->setParameter('id', $id);
        
        return $qb->getQuery()->getSingleResult();
    }     
}
