<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
