<?php

namespace ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getProducts($order = 'product.id')
    {
        $qb = $this->createQueryBuilder('product')
            ->select(
                  'product.id, '
                . 'product.name, '
                . 'product.description,'
                . 'product.price'
                )
            ->orderBy($order);
        
        return $qb->getQuery()->getScalarResult();
    }

}
